### ISSUE TITLE
Go To button URL field renders under the page

### ISSUE THREAD

**Issue by brkerd** [AutoFlowLabs/autoflow-studio-support#1]
The URL field prompted by the "Go To" button when recording tests renders under the page and blocks the user from entering the URL to go to. The URL field flashes for a second before the page is back on the screen. See video for more information
Screen Resolution: 1920 x 1080

https://github.com/user-attachments/assets/f1e82e32-a932-40f2-96ab-82d986f200a5

**Comment by rashiq05** [comment]
@brkerd 
Issue Description: The issue occurs because the dropdown state (setIsDropDownOpen(true)) is updated immediately after triggering the "hide-view" action via ipcRenderer.send. If "hide-view" takes time to process, it could lead to race conditions or UI inconsistencies where the dropdown appears prematurely or in an unintended state.

Proposed Solution: To resolve this, we introduced a setTimeout with a 500ms delay before opening the dropdown. This delay ensures that the "hide-view" action completes or has sufficient time to stabilize the UI state before the dropdown opens.

Key Points:

The setTimeout ensures the dropdown logic executes after any potential side effects of "hide-view" are settled.
The 500ms duration is chosen as a safe buffer but can be adjusted based on further testing or specific UI requirements.

Status Update: This issue has been fixed and the solution will be included in the next release, v0.2.8. Once the update is live, the fix will automatically resolve the reported issue.

https://github.com/user-attachments/assets/cb53e836-031f-46c7-a50c-af641e91d36d

**Comment by Bhavish77** [comment]
Using Electron's ipcRenderer.invoke and ipcMain.handle ensures sequential code execution by waiting for the "hide-view" action to complete before proceeding. This approach eliminates the need for a hardcoded 500ms delay, making the code more reliable and adaptable to varying processing times, while reducing the risk of race conditions and improving maintainability.

**Comment by SahilChoudhary22** [comment]
@brkerd This has been fixed and released with v0.2.8

Please check and feel free to re-open if the issue persists.
