### ISSUE TITLE
Test Status Discrepancy: Passed Tests Incorrectly Showing as FAILED_JOB on Windows

### ISSUE THREAD

**Issue by SahilChoudhary22** [AutoFlowLabs/autoflow-studio-support#3]
## Issues Description:
There is a critical inconsistency between test execution results and status reporting. While tests are successfully completing and marked as PASSED in the test results and reports, the test journey status incorrectly displays as FAILED_JOB in the UI.

## Steps to Reproduce:
- Run the affected test suite on a Windows environment
- Monitor test execution
- Check test results and journey status from the dropdown & history section
- Observe the discrepancy between passed tests and FAILED_JOB status
![image](https://github.com/user-attachments/assets/4ca51763-3a6e-4406-8620-b48c792f47ea)

Expected Behavior:
- Test journey status should reflect the actual test results
- PASSED tests should show a PASSED journey status

Current Behavior:
- Tests are executing successfully and marked as PASSED
- Journey status incorrectly shows FAILED_JOB despite successful test execution

## Environment Details:
- Operating System: Windows
- Application Version: v0.2.14

## Additional Notes:
- Issue appears to be Windows-specific
- Consistently reproducible with specific test cases
- The test run result is also shown as INTERRUPTED in v0.3.0

**Comment by himanshkukreja** [comment]
## Root Cause Analysis

1. Primary Issue:
   - JavaScript experimental warnings were incorrectly categorized as failures
   - These warnings were being written to `stderr`, triggering a FAILED_JOB status
   
2. Secondary Issue:
   - Race condition identified in status updating mechanism
   - Test statuses were being overwritten from PASSED/FAILED to INTERRUPTED
   - Journey statuses were similarly being overwritten from PASSED/FAILED to FAILED_JOB

## Solution Implemented:
1. Warning Handling:
   - Added proper handling for JavaScript experimental warnings
   - Prevented warning messages from being written to `stderr`
   - Implemented proper warning classification logic

2. Race Condition Fix:
   - Implemented status locking mechanism
   - Ensured status updates follow proper sequence
   - Added validation checks before status updates

## Verification:
- Confirmed test journeys now maintain correct status
- Verified warnings are properly handled without triggering failure states
- Validated status consistency across test execution lifecycle

## Additional Improvements:
- Enhanced warning message classification system

Please update to the latest version ([v0.3.2](https://autoflow.tools/downloads)) to receive these fixes. Monitor and report if any similar issues persist.

## Error Log/Screenshot:
![image](https://github.com/user-attachments/assets/19f7be45-8a33-4b21-8e8a-2270e1ef3d43)
